services:

  redis:
    image: redis:7-alpine
    container_name: auth-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  redis-ui:
    image: redis/redisinsight:latest
    container_name: auth-redis-ui
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  redis_data: