services:
  - type: web
    name: library-api
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: PORT
        sync: false
      - key: MONGO_URI
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true